export const CREATE_USER_SUCCESS = "CREATE_COURSE_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_AGENT_SUCCESS = "GET_AGENT_SUCCESS";
export const SAVE_MESSAGE_SUCCESS = "SAVE_MESSAGE_SUCCESS";